apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup1
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /backup/backup1-Jenkins
  
