apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume1
spec:
  capacity:
    storage: 350Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default 
  hostPath:
    path: /home/jenkins_home
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - "k8s-worker2"
