apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  resources:
    requests:
      storage: 250Gi
  storageClassName: default
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
