apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-slave-10
spec:
  capacity:
    storage: 550Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default 
  hostPath:
    path: /home/slave-10
  