apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup6-k10
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /backup/k106
  
