apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-slave-claim
  namespace: devops-tools
spec:
  resources:
    requests:
      storage: 500Gi
  storageClassName: default
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce