apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: {{ .Values.volumes.claimName }}
   namespace: {{ .Values.space.namespace }}
spec:
   storageClassName: default
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 500Gi

