apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.space.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      hostname: {{ .Values.host.name }}
      shareProcessNamespace: true
      containers:
      - name: jenkins-slave
        image: jamshidc/jchittan:jenkinsslave1.0
        resources:
          limits:
            memory: "10Gi"
            cpu: "3000m"

        ports:
        - containerPort: 22
        command: [ "/bin/bash" ]
        args: [ "-c",  "bash /home/scripts/install.sh;chown -R jenkinsuser:jenkinsuser /home/jenkinsuser;service ssh restart;tail -f /dev/null" ]
        volumeMounts:
        - name: pv-storage
          mountPath: /home/jenkinsuser
        - name: configmap-volume
          mountPath: /home/scripts/
   #     - name: configmap-volume
   #       subPath: authorized_keys
   #       mountPath: /home/jenkinsuser/.ssh/authorized_keys
        - name: configmap-volume
          subPath: authorized_root_keys
          mountPath: /root/.ssh/authorized_keys
   #     - name: configmap-volume
   #       subPath: config
   #       mountPath: /home/jenkinsuser/.ssh/config


      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.claimName }}
      - name: configmap-volume
        configMap:
          name: {{ .Values.configmap.name }}
