apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.volName }}
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default 
  hostPath:
    path: /home/{{ .Values.volumes.path }}
