apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.space.namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8080'
spec:
  selector:
    app: {{.Values.service.app }} 
  type: NodePort
  ports:
      - name: http
        port: 8080
        targetPort: 8080
        nodePort:
      - name: ssh
        port: 22
        nodePort: 
