apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxpv-claim1
  namespace: velero-test
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
