apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginxpv12
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  local:
    path: /backup/nginxpv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker2
  
