apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginxpv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  hostPath:
    path: /backup/nginxpv
  
